name: mlpipe

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8] # Change to your Python version

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8==3.9.0  # Pinning Flake8 version

    - name: Run Flake8 Linting
      run: |
        flake8 --max-line-length=100 .  # Adjust max-line-length as needed

    - name: Run tests with pytest
      run: |
        pytest
