name: mlpipe

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8] # Change to your Python version

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      uses: julianwachholz/flake8-action@v2.0.2
      with:
        checkName: 'flake8'
        path: '.'
        plugins: ''
        config: '.flake8'

    - name: Run tests with pytest
      run: |
        pytest
